# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cattr', '0001_initial'), ('cattr', '0002_auto_20151210_2233'), ('cattr', '0003_auto_20151210_2244'), ('cattr', '0004_cat_sex'), ('cattr', '0005_auto_20151210_2308'), ('cattr', '0006_posting_reservation'), ('cattr', '0007_auto_20151210_2312'), ('cattr', '0008_auto_20151210_2319'), ('cattr', '0009_auto_20151210_2320'), ('cattr', '0010_auto_20151211_1721'), ('cattr', '0011_posting_smokingenviron'), ('cattr', '0012_auto_20151211_1722')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('variety', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=300)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattr.Cat')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('', 'N/A'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('display', models.BooleanField()),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattr.Reservation')),
                ('smokingEnviron', models.BooleanField(default='no')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
    ]
