# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0003_auto_20151210_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('', 'N/A'), ('M', 'Male'), ('F', 'Female')], default='', max_length=2),
        ),
    ]
