# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0003_auto_20151212_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateField(),
        ),
    ]
