# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0005_auto_20151210_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattr.Reservation'),
        ),
    ]
