# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0005_auto_20151213_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattr.Cat')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattr.Cat'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cattr.Availability'),
        ),
    ]
