# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0007_auto_20151213_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.SmallIntegerField(max_length=30),
        ),
    ]
