# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0008_auto_20151213_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
