# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattr', '0010_auto_20151211_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='smokingEnviron',
            field=models.BooleanField(default='no'),
            preserve_default=False,
        ),
    ]
