# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 16:10
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('cattr', '0011_auto_20151214_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='tags',
        ),
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
