"""empty message

Revision ID: 3a866f86be65
Revises: 56f7e11642a6
Create Date: 2015-12-27 19:50:20.823856

"""

# revision identifiers, used by Alembic.
revision = '3a866f86be65'
down_revision = '56f7e11642a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_availability_cat_id'), 'availability', ['cat_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_cat_id'), table_name='availability')
    ### end Alembic commands ###
