"""empty message

Revision ID: 4d28bc29b41a
Revises: c64226128e39
Create Date: 2015-12-26 21:40:41.861540

"""

# revision identifiers, used by Alembic.
revision = '4d28bc29b41a'
down_revision = 'c64226128e39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    ### end Alembic commands ###
