"""empty message

Revision ID: 663a5930e280
Revises: a8e64689fb58
Create Date: 2015-12-29 15:24:17.135091

"""

# revision identifiers, used by Alembic.
revision = '663a5930e280'
down_revision = 'a8e64689fb58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    ### end Alembic commands ###
