"""empty message

Revision ID: 88ee0ef89e33
Revises: dbf7332d14c5
Create Date: 2015-12-26 21:26:31.510674

"""

# revision identifiers, used by Alembic.
revision = '88ee0ef89e33'
down_revision = 'dbf7332d14c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xref_cat_tag', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xref_cat_tag', sa.Column('id', sa.INTEGER(), nullable=False))
    ### end Alembic commands ###
