"""empty message

Revision ID: c28490d16b01
Revises: fab75b71b149
Create Date: 2015-12-27 00:52:51.673331

"""

# revision identifiers, used by Alembic.
revision = 'c28490d16b01'
down_revision = 'fab75b71b149'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'image')
    ### end Alembic commands ###
