"""empty message

Revision ID: c64226128e39
Revises: 88ee0ef89e33
Create Date: 2015-12-26 21:38:11.369553

"""

# revision identifiers, used by Alembic.
revision = 'c64226128e39'
down_revision = '88ee0ef89e33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    ### end Alembic commands ###
