"""empty message

Revision ID: dbf7332d14c5
Revises: 8059a052a15e
Create Date: 2015-12-26 15:04:46.262917

"""

# revision identifiers, used by Alembic.
revision = 'dbf7332d14c5'
down_revision = '8059a052a15e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('social_id', sa.String(length=64), nullable=False))
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_unique_constraint(None, 'users', ['social_id'])
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'nickname')
    ### end Alembic commands ###
