"""empty message

Revision ID: eb276c3fdce6
Revises: f39a91c25b91
Create Date: 2015-12-26 21:53:57.810747

"""

# revision identifiers, used by Alembic.
revision = 'eb276c3fdce6'
down_revision = 'f39a91c25b91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    ### end Alembic commands ###
