"""empty message

Revision ID: f39a91c25b91
Revises: 4d28bc29b41a
Create Date: 2015-12-26 21:42:36.462737

"""

# revision identifiers, used by Alembic.
revision = 'f39a91c25b91'
down_revision = '4d28bc29b41a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    ### end Alembic commands ###
