"""empty message

Revision ID: fab75b71b149
Revises: eb276c3fdce6
Create Date: 2015-12-26 22:45:44.927162

"""

# revision identifiers, used by Alembic.
revision = 'fab75b71b149'
down_revision = 'eb276c3fdce6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_cat_id_fkey', 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'cat_id')
    op.add_column('cats', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cats', 'addresses', ['address_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cats', type_='foreignkey')
    op.drop_column('cats', 'address_id')
    op.add_column('addresses', sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('addresses_cat_id_fkey', 'addresses', 'cats', ['cat_id'], ['id'])
    ### end Alembic commands ###
